#!/usr/bin/env bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/menu/qsmenu"
source "$SCRIPT_DIR/menu/wifi"

if [[ "$1" == "--connect" ]]; then
    wifi_connect_or_disconnect "$2"
else
    wifi_menu "$@"
fi
