# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = wofi -M fuzzy --show drun -i
$dmenu = wofi --show dmenu -k /dev/null -i -L 5 -M fuzzy --style ~/.config/wofi/dmenu.css
#$dmenu = | wofi --allow-markup --show dmenu 
$dmenuFormat = ~/src/enigmaOS/scripts/format_keys_wofi
$browser = chromium
$music = spotify
